### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by mcharudatta** [hofmannsven/mark-posts#17] opened 2021-06-19 07:29 UTC
I have a custom post that the plug-in detects. However, when I mark the topics, I don't see the color applied to them. Also, in the Quick Edit section, I do not see the option to set the marker to the topic.

**Comment by hofmannsven** [comment] 2021-06-21 19:41
Hey, can you please share the plugin version as well as the WordPress and PHP versions you're using?
Also, is the custom post type public or marked as _builtin_? Any information is helpful!

**Comment by mcharudatta** [comment] 2021-06-23 18:27
Below are the details:

Wordpress: 5.7.2

PHP: 7.4.6 (Supports 64bit values)

Using Custom Post Types from one theme with version 6.4.2. These custom posts are public.

***@***.***D7688B.76B6E700]


***@***.***D7688B.8ADCADA0]

Regards,
Charudatta S. Mundale

Business Owner | Consultant
+91 9922113311 | +91 20 67873020 | ***@***.******@***.***>
***@***.******@***.***>Chat with me on ***@***.***> | Upwork: freelancer profile<https://www.upwork.com/freelancers/~010635aec83f97d755>

**Comment by prastdon** [comment] 2021-11-23 15:38
Hi,

I have the same issue. The color doesn't show on Posts > All Posts.

**Comment by alpipego** [comment] 2022-03-08 02:21
@prastdon @mcharudatta if you're still using the plugin, is this consistent for all post types or only for specific ones? 

Just to make sure: Have you activated the markers for your post type on the settings page wp-admin/options-general.php?page=mark-posts?

**Comment by hofmannsven** [comment] 2022-09-14 22:01
I'm closing this issue because it has been inactive for a few months. This means that it is not reproducible or has been fixed in a newer version.

Please reopen if you still encounter this issue with the latest stable version of the plugin. You can also contribute directly by providing a patch. :)

Thank you!

**Closed by hofmannsven** 2022-09-14 22:01 UTC
